version: "3.9"

services:
  redis:
    image: redis:6.2
    container_name: local-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: ["redis-server", "--appendonly", "yes"]

  mysql:
    image: mysql:8.0
    container_name: local-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: catfe
      MYSQL_USER: catfe_user
      MYSQL_PASSWORD: catfe_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  redis_data:
  mysql_data: