spring:
  datasource:
    url: jdbc:h2:mem:db_test;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}

  sql:
    init:
      mode: never

  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: dummy-kakao-client-id
            authorization-grant-type: authorization_code
            client-name: Kakao
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: profile_nickname, profile_image, account_email
          naver:
            client-id: dummy-naver-client-id
            client-secret: dummy-naver-client-secret
            client-name: Naver
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: email, nickname, profile_image
          google:
            client-id: dummy-google-client-id
            client-secret: dummy-google-client-secret
            client-name: Google
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope:
              - email
              - profile
          github:
            client-id: dummy-github-client-id
            client-secret: dummy-github-client-secret
            client-name: GitHub
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/{registrationId}"
            scope: user:email
        provider:
          kakao:
            authorization-uri: https://kauth.kakao.com/oauth/authorize
            token-uri: https://kauth.kakao.com/oauth/token
            user-info-uri: https://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: https://nid.naver.com/oauth2.0/authorize
            token-uri: https://nid.naver.com/oauth2.0/token
            user-info-uri: https://openapi.naver.com/v1/nid/me
            user-name-attribute: response
          google:
            authorization-uri: https://accounts.google.com/o/oauth2/v2/auth
            token-uri: https://oauth2.googleapis.com/token
            user-info-uri: https://www.googleapis.com/oauth2/v3/userinfo
            user-name-attribute: sub
          github:
            authorization-uri: https://github.com/login/oauth/authorize
            token-uri: https://github.com/login/oauth/access_token
            user-info-uri: https://api.github.com/user
            user-name-attribute: id

  mail:
    host: smtp.test.com
    port: 1025
    username: test
    password: test
    properties:
      mail:
        smtp:
          auth: false
          starttls:
            enable: false

jwt:
  secret: test-jwt-secret-key-12345678901234567890
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:1800}  # 30분 (초 단위)
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800}  # 7일 (초 단위)

frontend:
  base-url: http://localhost:3000

# AWS S3
cloud:
  aws:
    region:
      static: ap-northeast-2

    s3:
      bucket: bucket-name

    stack:
      auto: false