spring:
  datasource:
    url: jdbc:h2:./db_dev;MODE=MySQL
    driver-class-name: org.h2.Driver
    username: sa
    password:

  data:
    redis:
      host: localhost
      port: 6379

  config:
    import: optional:file:.env[.properties]

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update      # [none | validate | update | create | create-drop]
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true

springdoc:
  default-produces-media-type: application/json;charset=UTF-8

logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.web.socket: DEBUG
    org.springframework.messaging: DEBUG

jwt:
  secret: ${JWT_SECRET:test-jwt-secret-key-12345678901234567890} # 운영 시에는 반드시 환경 변수로 설정할 것
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION:1800}  # 30분 (초 단위)
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION:604800}  # 7일 (초 단위)

# 스터디룸 설정
studyroom:
  heartbeat:
    timeout-minutes: 5  # Heartbeat 타임아웃 (분)
  default:
    max-participants: 10  # 기본 최대 참가자 수
    allow-camera: true
    allow-audio: true
    allow-screen-share: true