name: PR Build & Test

# PR 이벤트 트리거 (main, dev 브랜치 대상으로)
on:
  pull_request:
    branches:
      - main
      - dev
    types: [opened, synchronize, reopened]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    services:
      redis:
        image: redis:7
        ports:
          - 6379:6379

      mysql:
        image: mysql:8
        ports:
          - 3306:3306
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: testdb
        options: >-
          --health-cmd="mysqladmin ping -h localhost -p$MYSQL_ROOT_PASSWORD"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
      # 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # Java 21 설치
      - name: Set up Java 21
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'   # Eclipse Temurin JDK
          java-version: '21'        # Gradle build.gradle toolchain에 맞춤

      # .env 파일 생성
      - name: Create .env file
        run: echo "${{ secrets.DOT_ENV }}" > .env

      # Build (테스트 제외)
      - name: Build project
        run: ./gradlew clean build -x test

      # Test 실행
      - name: Run tests
        run: ./gradlew test